version: '1.0'
services:
  json-worker:
    build:
      context: ./worker
      args:
        format: json
  msgpack-worker:
    build:
      context: ./worker
      args:
        format: msgpack
  yaml-worker:
    build:
      context: ./worker
      args:
        format: yaml
  avro-worker:
    build:
      context: ./worker
      args:
        format: avro
  protobuf-worker:
    build:
      context: ./worker
      args:
        format: protobuf
  api:
    build:
      context: ./api
    ports:
      - 2000:2000/udp
    